apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 004271464911.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newName: 004271464911.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newTag: e259197f
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
